server:
  port: 8081
  servlet:
    context-path: /digital-bankx

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bankx
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: validate
      dialect: org.hibernate.dialect.MySQLDialect
  cloud:
    aws:
      endpoint: http://localhost:4566
      credentials:
        profile:
          name: localstack
      region:
        static: sa-east-1
      s3:
        endpoint: http://s3.localhost.localstack.cloud:4566
      sqs:
        endpoint: http://localhost:4566
  batch:
    jdbc:
      initialize-schema: always

logging:
  level:
    root: info
    org:
      springframework:
      web: info

cloud:
  aws:
    sqs:
      queues:
        bankx-transactions: SQS-BankX-Transactions

